# Generated by Django 4.2.3 on 2024-04-04 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_booking_date_time_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sr',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
